### PR TITLE
Fix detection of rootless Docker

### PR DESCRIPTION
**Pull request by SanjayVas**
This treats Docker Desktop for Mac as rootless as well as fixing rootless detection for Podman.

### CODE REVIEW

**Comment by SanjayVas** [comment]
Once this and #69 are in, I think #60 can be closed.

**Comment by wangyaopw** [comment]
oops, I accidentally clicked "pushed to origin" in the github desktop, and now this branch got several extra commits.

Is there a way to delete a remote commit?

------------
Now my actual comment,

with this and #69, 
```
DOCKER="$HOME/bin/docker-wrapper" tools/bazel-container test //src/test/cc/...
```
passes

but 
```
DOCKER="$HOME/bin/docker-wrapper" tools/bazel-container test //src/test/kotlin/org/wfanet/measurement/common/grpc:TransportSecurityTest
```
is still failing with 
```
ERROR: /Users/wangyaopw/Documents/GitHub/experimental/cross-media-measurement/imports/kotlin/io/grpc/health/v1/BUILD.bazel:5:20: TreeArtifact imports/kotlin/io/grpc/health/v1/health_kt_jvm_grpc_DO_NOT_DEPEND_kt_grpc/ktgrpc was not created
ERROR: /Users/wangyaopw/Documents/GitHub/experimental/cross-media-measurement/imports/kotlin/io/grpc/health/v1/BUILD.bazel:5:20: Generating Kotlin gRPC extensions for @io_grpc_grpc_proto//:health_proto failed: not all outputs were created or valid
```

**Comment by SanjayVas** [comment]
> oops, I accidentally clicked "pushed to origin" in the github desktop, and now this branch got several extra commits.
> 
> Is there a way to delete a remote commit?

Yes, force pushing. I went ahead and did this.

> with this and #69,
> 
> ```
> DOCKER="$HOME/bin/docker-wrapper" tools/bazel-container test //src/test/cc/...
> ```
> 
> passes
> 
> but
> 
> ```
> DOCKER="$HOME/bin/docker-wrapper" tools/bazel-container test //src/test/kotlin/org/wfanet/measurement/common/grpc:TransportSecurityTest
> ```
> 
> is still failing with
> 
> ```
> ERROR: /Users/wangyaopw/Documents/GitHub/experimental/cross-media-measurement/imports/kotlin/io/grpc/health/v1/BUILD.bazel:5:20: TreeArtifact imports/kotlin/io/grpc/health/v1/health_kt_jvm_grpc_DO_NOT_DEPEND_kt_grpc/ktgrpc was not created
> ERROR: /Users/wangyaopw/Documents/GitHub/experimental/cross-media-measurement/imports/kotlin/io/grpc/health/v1/BUILD.bazel:5:20: Generating Kotlin gRPC extensions for @io_grpc_grpc_proto//:health_proto failed: not all outputs were created or valid
> ```
Hmm, I'm surprised this fails to build for you on Docker Desktop for Mac. I was able to get this test to build and pass on Docker on Linux (both rootless and not). The only things that I can think of accounting for the differences are either the Linux VM that's a part of Docker Desktop for Mac, or some additional interaction with the host filesystem. Perhaps try running with `--verbose_failures` and see if it gives more details?

**Comment by wangyaopw** [comment]
> > oops, I accidentally clicked "pushed to origin" in the github desktop, and now this branch got several extra commits.
> > Is there a way to delete a remote commit?
> 
> Yes, force pushing. I went ahead and did this.
> 
> > with this and #69,
> > ```
> > DOCKER="$HOME/bin/docker-wrapper" tools/bazel-container test //src/test/cc/...
> > ```
> > 
> > 
> > passes
> > but
> > ```
> > DOCKER="$HOME/bin/docker-wrapper" tools/bazel-container test //src/test/kotlin/org/wfanet/measurement/common/grpc:TransportSecurityTest
> > ```
> > 
> > 
> > is still failing with
> > ```
> > ERROR: /Users/wangyaopw/Documents/GitHub/experimental/cross-media-measurement/imports/kotlin/io/grpc/health/v1/BUILD.bazel:5:20: TreeArtifact imports/kotlin/io/grpc/health/v1/health_kt_jvm_grpc_DO_NOT_DEPEND_kt_grpc/ktgrpc was not created
> > ERROR: /Users/wangyaopw/Documents/GitHub/experimental/cross-media-measurement/imports/kotlin/io/grpc/health/v1/BUILD.bazel:5:20: Generating Kotlin gRPC extensions for @io_grpc_grpc_proto//:health_proto failed: not all outputs were created or valid
> > ```
> 
> Hmm, I'm surprised this fails to build for you on Docker Desktop for Mac. I was able to get this test to build and pass on Docker on Linux (both rootless and not). The only things that I can think of accounting for the differences are either the Linux VM that's a part of Docker Desktop for Mac, or some additional interaction with the host filesystem. Perhaps try running with `--verbose_failures` and see if it gives more details?

**Review by wangyaopw — APPROVED** [review]

**Comment by SanjayVas** [comment]
> I guess this is also related to [bazelbuild/bazel#6393](https://github.com/bazelbuild/bazel/issues/6393)

This isn't using remote execution. We're doing a local build inside of a Docker container.

**Pull request merged**
